name: ncon_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.2
  table_calendar: ^3.0.9
  intl: ^0.20.2
  dotted_border: ^3.1.0
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/splash_logo.png

# Native splash screen config
flutter_native_splash:
  color: "#0000FF"             # Background color (blue)
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: true

# App icon config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_logo.png
